1.2.3 Retour sur la page précédente
SchoodEIP/Schood-WEB pull request #61
Opened 2023-07-30 16:28 UTC by adbusnel

Création d'un composant permettant de retourner sur la page précédente

2023-08-27 02:26 UTC, Exiels requested changes
Use camelCase for file name

2023-08-27 02:26 UTC, Exiels commented on src/Components/Buttons/PreviousPage.jsx
Use camelCase

2023-08-27 02:26 UTC, Exiels commented on src/Users/Public/ForgottenPasswordPage.jsx
Use camelCase

2023-08-27 02:26 UTC, Exiels commented on src/Users/Public/NoPage.jsx
Use camelCase

2023-08-27 02:26 UTC, Exiels commented on src/__tests__/Components/Buttons/PreviousPage.test.jsx
Use camelCase

2023-08-27 02:26 UTC, Exiels commented on src/__tests__/Users/Public/NoPage.test.js
Use camelCase

2023-08-31 22:41 UTC, adbusnel commented on src/Components/Buttons/PreviousPage.jsx
resolu dans la branche account_creation

2023-08-31 22:42 UTC, adbusnel commented on src/Users/Public/ForgottenPasswordPage.jsx
resolu dans la branche account_creation

2023-08-31 22:42 UTC, adbusnel commented on src/Users/Public/NoPage.jsx
resolu dans la branche account_creation

2023-08-31 22:42 UTC, adbusnel commented on src/__tests__/Components/Buttons/PreviousPage.test.jsx
resolu dans la branche account_creation

2023-08-31 22:42 UTC, adbusnel commented on src/__tests__/Users/Public/NoPage.test.js
resolu dans la branche account_creation

2023-09-01 22:52 UTC, merged